# Generated by Django 4.2.6 on 2023-10-23 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('K', 'kids')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.gender'),
        ),
    ]
