# Generated by Django 4.2.6 on 2023-10-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_gender_name_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
